import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.scss";
import Link from 'next/link';
import styles from "./page.module.scss";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

async function getPages() {
  const res = await fetch('http://localhost:8888/wp-json/wp/v2/pages')

  if (!res.ok) {
    throw new Error('Failed to fetch data')
  }
 
  return res.json()
}

async function getPosts() {
  const res = await fetch('http://localhost:8888/wp-json/wp/v2/posts')

  if (!res.ok) {
    throw new Error('Failed to fetch data')
  }
 
  return res.json()
}

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const pages = await getPages()
  const posts = await getPosts()

  return (
    <html lang="en">
      <body className={inter.className}>
        <header className={styles.header}>
        <Link href="/">
          <h1 className={styles.logo}>🎉 Movies</h1>
        </Link>
          <nav>
            <ul className={styles.navList}>
              {pages.map((page: any) => (
                <li><Link href={`/page/${page.id}`}>{page.title.rendered}</Link></li>
              ))}
            </ul>
          </nav>
        </header>
        {children}
        <footer className={styles.footer}>
          <h2 className={styles.footerTitle}>Explore Our Posts</h2>
          <ul>
            {posts.map((post: any) => (
              <li key={post.id}>
                <Link href={`/post/${post.id}`}>
                  {post.title.rendered}
                </Link>
              </li>
            ))}
          </ul>
        </footer>
      </body>
    </html>
  );
}
